name = "render-keepalive-cloudflare"
main = "src/index.js"
compatibility_date = "2024-12-24"  # Changed from 2025-12-25

[triggers]
crons = ["*/5 * * * *"]

[vars]
RENDER_URL = "https://pokemon.onrender.com"
